
SELECT *
FROM ASSESSMENT_DB.PUBLIC_RAW.CUSTOMER_DETAILS;

SELECT *
FROM ASSESSMENT_DB.PUBLIC_RAW.ORDER_DETAILS;

SELECT * 
FROM  ASSESSMENT_DB.PUBLIC_RAW.SHIPPING_DETAILS;

--Create temp table for JSON PARSING
USE ASSESSMENT_DB;
USE SCHEMA PUBLIC_RAW;
CREATE TEMPORARY TABLE JSON_PARSING AS 
SELECT
    JASON_SHIPPING:Customer_ID::VARCHAR        AS CUSTOMER_ID,
    JASON_SHIPPING:Shipping_ID::VARCHAR        AS SHIPPING_ID,
    JASON_SHIPPING:Status::VARCHAR         AS STATUS
FROM ASSESSMENT_DB.PUBLIC_RAW.SHIPPING_DETAILS
ORDER BY CUSTOMER_ID
;


---------------------------------------------------------------------------------------------------------------------------------------------------------
---UNDERSTANDING THE DATA
---------------------------------------------------------------------------------------------------------------------------------------------------------
SELECT * FROM ASSESSMENT_DB.PUBLIC_RAW.CUSTOMER_DETAILS;

SELECT * FROM ASSESSMENT_DB.PUBLIC_RAW.ORDER_DETAILS;

SELECT * FROM ASSESSMENT_DB.PUBLIC_RAW.SHIPPING_DETAILS_PARSED;

--Understanding the data: Check to see if each customer has single/multiple shipping ID
SELECT CUSTOMER_ID,
COUNT(DISTINCT SHIPPING_ID) AS SHIPPING_COUNT
FROM JSON_PARSING  
GROUP BY 1 
HAVING COUNT(DISTINCT SHIPPING_ID) > 1
ORDER BY SHIPPING_COUNT DESC;

--Understanding the data: Check to see if each order has single/multiple shipping ID
SELECT ORDER_ID,
COUNT(DISTINCT SHIPPING_ID) AS SHIPPING_COUNT
FROM JSON_PARSING A 
JOIN ASSESSMENT_DB.PUBLIC_RAW.ORDER_DETAILS B
ON A.CUSTOMER_ID = B.CUSTOMER_ID
GROUP BY 1 
HAVING COUNT(DISTINCT SHIPPING_ID) > 1
ORDER BY SHIPPING_COUNT DESC;



SELECT *
FROM JSON_PARSING A 
JOIN ASSESSMENT_DB.PUBLIC_RAW.ORDER_DETAILS B
ON A.CUSTOMER_ID = B.CUSTOMER_ID;


SELECT *
FROM  ASSESSMENT_DB.PUBLIC_RAW.ORDER_DETAILS
WHERE CUSTOMER_ID='35';

SELECT *
FROM json_parsing
where customer_id = 35;

---Has 4 shipments for just one order of item "Keyboard"..of which 3 are pending and 1 is delivered:Pending  likely represent unprocessed, superseded, or system-generated shipment attempts rather than actual shipments..

--Customer having multiple orders...and if the same customer has multiple shipping ID's ...how do we map the shipping ID's to those orders..? big q
WITH MORE_THAN_ONE_ORDER AS (
SELECT A.*,B.ORDER_ID
FROM ASSESSMENT_DB.PUBLIC_RAW.CUSTOMER_DETAILS A
JOIN ASSESSMENT_DB.PUBLIC_RAW.ORDER_DETAILS B
ON A.CUSTOMER_ID = B.CUSTOMER_ID
QUALIFY ROW_NUMBER() OVER (PARTITION BY A.CUSTOMER_ID ORDER BY ORDER_ID) >1
)

SELECT A.CUSTOMER_ID, COUNT(DISTINCT SHIPPING_ID) AS SHIPPING_COUNT
FROM MORE_THAN_ONE_ORDER  A
JOIN JSON_PARSING B
ON A.CUSTOMER_ID = B.CUSTOMER_ID
GROUP BY 1
ORDER BY SHIPPING_COUNT DESC;

SELECT * FROM ASSESSMENT_DB.PUBLIC_RAW.ORDER_DETAILS
WHERE CUSTOMER_ID='85';

SELECT * FROM JSON_PARSING WHERE CUSTOMER_ID='85';

-----------------------------------------------------------------------
--How many items per order

SELECT ORDER_ID, 
COUNT(DISTINCT ITEM) AS ITEMS_PER_ORDER

FROM ASSESSMENT_DB.PUBLIC_RAW.ORDER_DETAILS
GROUP BY 1
ORDER BY ITEMS_PER_ORDER DESC;

------------------------------------------------------------------------
SELECT COUNT(DISTINCT ORDER_ID),
COUNT(DISTINCT CUSTOMER_ID)
FROM ASSESSMENT_DB.PUBLIC_RAW.ORDER_DETAILS

--Note
--Single order has multiple shipping IDs---Solvable: Assign 0 to pending and 1 to delivered..and take max
--Multiple orders have single shipping ID --Undeterministic 
--Multiple Orders also have multiple shipping ID's :
          --Partially solvable: Number of orders = Number of Delivered shipping IDs then Delivered
          --                  : If no Delivered event then Pending
          --                  : If number of  Delivered shipping ID's are less than the number of orders then we cannot determine which of the orders are delivered and which of them did not get delivered
--There are shipping ID's for customers who has no orders: Anomolies

----------------------------------------------------------------------------------------------------------------------------------------

SELECT ORDER_ID
FROM ASSESSMENT_DB.PUBLIC_RAW.ORDER_DETAILS
GROUP BY 1
HAVING COUNT(ITEM)>1;

WITH MORE_THAN_ONE_ORDER AS (
SELECT DISTINCT  A.CUSTOMER_ID
FROM ASSESSMENT_DB.PUBLIC_RAW.CUSTOMER_DETAILS A
JOIN ASSESSMENT_DB.PUBLIC_RAW.ORDER_DETAILS B
ON A.CUSTOMER_ID = B.CUSTOMER_ID
GROUP BY A.CUSTOMER_ID
HAVING COUNT(DISTINCT ORDER_ID) >1


)
SELECT DISTINCT A.CUSTOMER_ID
FROM MORE_THAN_ONE_ORDER  A
JOIN ASSESSMENT_DB.PUBLIC_RAW.SHIPPING_DETAILS_PARSED B
ON A.CUSTOMER_ID = B.CUSTOMER_ID
GROUP BY A.CUSTOMER_ID
HAVING COUNT(DISTINCT SHIPPING_ID) >=1;

----Customers and their corresponding Orders and shipping count whose status are undeterministic
WITH MORE_THAN_ONE_ORDER AS (
SELECT DISTINCT  A.CUSTOMER_ID
FROM ASSESSMENT_DB.PUBLIC_RAW.CUSTOMER_DETAILS A
JOIN ASSESSMENT_DB.PUBLIC_RAW.ORDER_DETAILS B
ON A.CUSTOMER_ID = B.CUSTOMER_ID
GROUP BY A.CUSTOMER_ID
HAVING COUNT(DISTINCT ORDER_ID) >1


)
,  MORE_THAN_ONE_SHIPPING_ID AS (
SELECT DISTINCT A.CUSTOMER_ID
FROM MORE_THAN_ONE_ORDER  A
JOIN ASSESSMENT_DB.PUBLIC_RAW.SHIPPING_DETAILS_PARSED B
ON A.CUSTOMER_ID = B.CUSTOMER_ID
GROUP BY A.CUSTOMER_ID
--HAVING COUNT(DISTINCT SHIPPING_ID) >1

)
, SUMMARY AS (
SELECT A.CUSTOMER_ID,
COUNT(DISTINCT SHIPPING_ID) AS TOTAL_SHIPPING_IDS,
COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
COUNT(DISTINCT CASE WHEN UPPER(TRIM(STATUS)) = 'DELIVERED' THEN SHIPPING_ID END) AS DELIVERED_SHIPPING_ID,
COUNT(DISTINCT CASE WHEN UPPER(TRIM(STATUS)) = 'PENDING' THEN SHIPPING_ID END) AS PENDING_SHIPPING_ID,
FROM MORE_THAN_ONE_SHIPPING_ID A
JOIN ASSESSMENT_DB.PUBLIC_RAW.SHIPPING_DETAILS_PARSED B 
ON A.CUSTOMER_ID = B.CUSTOMER_ID
JOIN ASSESSMENT_DB.PUBLIC_RAW.ORDER_DETAILS C
ON A.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY 1
)
---Orders which are undeterministic
SELECT CUSTOMER_ID,
TOTAL_ORDERS,
TOTAL_SHIPPING_IDS,
DELIVERED_SHIPPING_ID,
PENDING_SHIPPING_ID
FROM SUMMARY
WHERE NOT(DELIVERED_SHIPPING_ID=0 OR PENDING_SHIPPING_ID=0 OR DELIVERED_SHIPPING_ID=TOTAL_ORDERS)
ORDER BY CUSTOMER_ID;

-----------------------------------------------------------------------------------------------------------------------






SELECT * FROM ASSESSMENT_DB.PUBLIC_RAW.ORDER_DETAILS WHERE CUSTOMER_ID='12';
SELECT * FROM ASSESSMENT_DB.PUBLIC_RAW.SHIPPING_DETAILS_PARSED WHERE CUSTOMER_ID='12';

SELECT STATUS,COUNT(*) FROM JSON_PARSING GROUP BY 1;

WITH MORE_THAN_ONE_ORDER AS (
SELECT DISTINCT  A.CUSTOMER_ID
FROM ASSESSMENT_DB.PUBLIC_RAW.CUSTOMER_DETAILS A
JOIN ASSESSMENT_DB.PUBLIC_RAW.ORDER_DETAILS B
ON A.CUSTOMER_ID = B.CUSTOMER_ID
GROUP BY A.CUSTOMER_ID
HAVING COUNT(DISTINCT ORDER_ID) >1


)
,  MORE_THAN_ONE_SHIPPING_ID AS (
SELECT DISTINCT A.CUSTOMER_ID
FROM MORE_THAN_ONE_ORDER  A
JOIN ASSESSMENT_DB.PUBLIC_RAW.SHIPPING_DETAILS_PARSED B
ON A.CUSTOMER_ID = B.CUSTOMER_ID
GROUP BY A.CUSTOMER_ID
HAVING COUNT(DISTINCT SHIPPING_ID) >1
)
;
WITH DELIEVERED AS(
SELECT CUSTOMER_ID,COUNT(DISTINCT SHIPPING_ID) AS CNT
FROM ASSESSMENT_DB.PUBLIC_RAW.SHIPPING_DETAILS_PARSED
WHERE UPPER(TRIM(STATUS))='DELIVERED'
GROUP BY 1
)

, ORDERS AS (SELECT CUSTOMER_ID,COUNT(DISTINCT order_id) AS CNT
FROM ASSESSMENT_DB.PUBLIC_RAW.ORDER_DETAILS
GROUP BY 1)
SELECT A.*
FROM DELIEVERED A JOIN ORDERS B ON A.CUSTOMER_ID=B.CUSTOMER_ID
WHERE A.CNT>B.CNT;


SELECT DISTINCT ORDER_ID,
 A.CUSTOMER_ID
FROM ASSESSMENT_DB.PUBLIC_RAW.ORDER_DETAILS A
LEFT JOIN ASSESSMENT_DB.PUBLIC_RAW.SHIPPING_DETAILS_PARSED B
ON A.CUSTOMER_ID = B.CUSTOMER_ID
WHERE B.CUSTOMER_ID IS NULL;